require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Max: 15
